### ISSUE TITLE
(Design request) Store the configuration files on XDG-compliant directories

### ISSUE THREAD

**Issue by hardBSDk** [slerpyyy/sh4der-jockey#8]
Store the configuration files at `/usr/share/sh4der-jockey` or `~/.local/share/sh4der-jockey` on Linux/BSD will allow this program to be packaged on operating systems package repositories.

**Comment by slerpyyy** [comment]
Ah, good point! I've been meaning to change the location of the config files for a long time, but never came around to it.

I've just pushed a commit (2cda74157741d64197383fd86a32b80f6cb22e58) to main, which implements the following strategy:

- If the environment variable `SH4DER_DIR` resolves to a valid folder path, use that folder for all config files
- Otherwise, if there are already config files in the same folder as the executable, use that folder for backwards compatibility
- Otherwise, attempt to resolve and use the default local config folder for the appropriate system, which is
  - `$XDG_CONFIG_HOME/sh4der-jockey` or `$HOME/.config/sh4der-jockey` on Linux, and
  - `{FOLDERID_LocalAppData}/sh4der-jockey` on Windows
- Otherwise, give up, do not load or store any config files and tell the user to set `SH4DER_DIR`

Are you happy with this system, or should I change anything else?

**Comment by hardBSDk** [comment]
@slerpyyy It's very good! backwards-compatibility is important.
